# Generated by Django 4.0.3 on 2022-03-29 13:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airline_companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Economy class', 'Economy class'), ('Business class', 'Business class'), ('First class', 'First class')], max_length=14)),
                ('available_seats', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TicketBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('passport_id', models.CharField(max_length=255)),
                ('issued_passport', models.CharField(max_length=255)),
                ('period_of_validity', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('refused', 'Refused'), ('pending', 'Pending')], default='pending', max_length=255)),
                ('seat', models.PositiveIntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airline_companies.flight')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.typeclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
