# Generated by Django 4.0.3 on 2022-03-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_id_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AviaCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('number_of_seat', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('place_of_departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='cities_light.city')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('total_available_seats', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avia_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airline_companies.aviacompany')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='airline_companies.point')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airline_companies.plane')),
            ],
        ),
        migrations.CreateModel(
            name='AviaCompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avia_photo')),
                ('avia_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='airline_companies.aviacompany')),
            ],
        ),
    ]
